// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv387Oh0Cs4NzMXN5ezlXP0o2GohWN9VI',
    appId: '1:478217884282:web:e17a6ba9b02cbb53fa21c3',
    messagingSenderId: '478217884282',
    projectId: 'mealmentor-d2096',
    authDomain: 'mealmentor-d2096.firebaseapp.com',
    databaseURL: 'https://mealmentor-d2096-default-rtdb.firebaseio.com',
    storageBucket: 'mealmentor-d2096.appspot.com',
    measurementId: 'G-FPD3HNWNS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAavcmShgxqvPBO9LRyHhrimjYBo9LhCww',
    appId: '1:478217884282:android:7b54fbe15fd43b31fa21c3',
    messagingSenderId: '478217884282',
    projectId: 'mealmentor-d2096',
    databaseURL: 'https://mealmentor-d2096-default-rtdb.firebaseio.com',
    storageBucket: 'mealmentor-d2096.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUudgnxE1pGdIAG3e0oon2QokHuHkat9I',
    appId: '1:478217884282:ios:8ba0ed28545cb2a3fa21c3',
    messagingSenderId: '478217884282',
    projectId: 'mealmentor-d2096',
    databaseURL: 'https://mealmentor-d2096-default-rtdb.firebaseio.com',
    storageBucket: 'mealmentor-d2096.appspot.com',
    iosBundleId: 'com.example.mealmentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUudgnxE1pGdIAG3e0oon2QokHuHkat9I',
    appId: '1:478217884282:ios:0a379b6b2efe4c01fa21c3',
    messagingSenderId: '478217884282',
    projectId: 'mealmentor-d2096',
    databaseURL: 'https://mealmentor-d2096-default-rtdb.firebaseio.com',
    storageBucket: 'mealmentor-d2096.appspot.com',
    iosBundleId: 'com.example.mealmentor.RunnerTests',
  );
}
